apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: unity-android-build

on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Checkout
        uses: https://github.com/cloudbees-io/checkout@v1
        with:
          repository: lsa26/AngryBirdsRemakeUnity
          ref: main
      
      - name: Build with Unity
        uses: docker://unityci/editor:ubuntu-2020.1.1f1-android-0.3.0
        shell: bash
        run: |
          # Créer les répertoires nécessaires
          mkdir -p "${CLOUDBEES_WORKSPACE}/Builds/Android"
          
          # Vérifier l'installation Unity
          ls -la /opt/unity/Editor/
          
          # Exécuter Unity avec le script de build
          echo "Exécution du build Unity..."
          /opt/unity/Editor/Unity \
            -batchmode \
            -nographics \
            -projectPath "${CLOUDBEES_WORKSPACE}" \
            -logFile "${CLOUDBEES_WORKSPACE}/unity_build.log" \
            -executeMethod BuildScript.BuildAndroid \
            -quit
          
          # Capture le code de sortie
          BUILD_RESULT=$?
          
          # Afficher le log complet
          if [ -f "${CLOUDBEES_WORKSPACE}/unity_build.log" ]; then
            echo "=== Log de build Unity ==="
            cat "${CLOUDBEES_WORKSPACE}/unity_build.log"
            echo "======================="
          else
            echo "Aucun log de build trouvé"
          fi
          
          # Vérifier la sortie
          echo "Contenu du dossier de build:"
          find "${CLOUDBEES_WORKSPACE}/Builds" -type f | sort
          
          # Terminer avec le bon code de sortie
          exit $BUILD_RESULT
      
      - name: Archive Android Build
        if: success()
        uses: https://github.com/cloudbees-io/store-artifacts@v1
        with:
          path: ${CLOUDBEES_WORKSPACE}/Builds/Android/AngryBirdsRemake.apk
          name: AngryBirdsRemake.apk