apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: unity-android-build-diagnostic

on:
  workflow_dispatch:

jobs:
  diagnose:
    steps:
      - name: Docker image diagnostic
        uses: docker://unityci/editor:2020.1.17f1-android-0.17.0
        shell: bash
        run: |
          echo "Information système:"
          uname -a
          cat /etc/os-release
          
          echo "Recherche de l'installation Unity:"
          find / -name "Unity" -type d 2>/dev/null || echo "Aucun répertoire Unity trouvé"
          find / -name "unity" -type f 2>/dev/null || echo "Aucun exécutable unity trouvé"
          
          echo "Recherche de fichiers potentiellement liés à Unity:"
          find / -name "*unity*" -type f 2>/dev/null | grep -v ".log" | head -20 || echo "Aucun fichier unity trouvé"
          
          echo "Liste des répertoires principaux:"
          ls -la / || echo "Impossible de lister le contenu de /"
          
          echo "Liste du contenu de /opt (si disponible):"
          if [ -d "/opt" ]; then
            ls -la /opt/
          else
            echo "/opt n'existe pas"
          fi
