apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: unity-android-build-alternative

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Checkout
        uses: https://github.com/cloudbees-io/checkout@v1
        with:
          repository: lsa26/AngryBirdsRemakeUnity
          ref: main
      
      # Utiliser l'approche du Game CI
      - name: Build with Unity using GameCI
        uses: docker://game-ci/unity-builder:ubuntu-2020.1.17f1-android-0.17.0
        with:
          projectPath: "${CLOUDBEES_WORKSPACE}"
          targetPlatform: Android
          buildName: AngryBirdsRemake
          buildMethod: BuildScript.Build
        env:
          UNITY_LICENSE: 'PERSONAL'
