apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: unity-android-build

on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Build Unity Android Game
        uses: ./unity-build-action  # Chemin vers l'action personnalisée
        with:
          repository: lsa26/AngryBirdsRemakeUnity
          ref: main
          unity_version: ubuntu-2020.1.1f1-android-0.3.0
          output_name: AngryBirdsRemake.apk
          bundle_id: com.yourgame.angrybirdsremake
          scenes: Assets/Scenes/MainMenu.unity,Assets/Scenes/Level1.unity,Assets/Scenes/Level2.unity
