apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: unity-android-build

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Checkout
        uses: https://github.com/cloudbees-io/checkout@v1
        with:
          repository: lsa26/AngryBirdsRemakeUnity
          ref: main

      - name: Build with Unity in custom container
        uses: docker://gableroux/unity3d:2020.1.1f1-android
        shell: bash
        run: |
          # Créer un répertoire pour les builds
          mkdir -p "${CLOUDBEES_WORKSPACE}/Builds/Android"
          
          # Activer Unity en mode personnel (sans license file)
          echo "Configuration de Unity en licence personnelle..."
          xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' \
            /opt/Unity/Editor/Unity \
              -batchmode \
              -createManualActivationFile \
              -logFile /tmp/unity-manual-activation.log \
              -quit
          
          # Afficher la structure du projet
          echo "Structure du projet Unity :"
          find "${CLOUDBEES_WORKSPACE}" -type f -name "*.unity" | sort
          
          # Effectuer le build avec xvfb pour émuler un écran
          echo "Démarrage du build Unity..."
          xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' \
            /opt/Unity/Editor/Unity \
              -batchmode \
              -nographics \
              -projectPath "${CLOUDBEES_WORKSPACE}" \
              -logFile "${CLOUDBEES_WORKSPACE}/unity_build.log" \
              -executeMethod BuildScript.Build \
              -quit
          
          # Vérifier le résultat et afficher le log
          BUILD_RESULT=$?
          if [ -f "${CLOUDBEES_WORKSPACE}/unity_build.log" ]; then
            echo "Log de build Unity :"
            cat "${CLOUDBEES_WORKSPACE}/unity_build.log"
          else
            echo "Fichier de log non trouvé"
          fi
          
          # Vérifier si des APK ont été générés
          find "${CLOUDBEES_WORKSPACE}/Builds" -name "*.apk" | while read apk; do
            echo "APK généré: $apk"
            ls -lh "$apk"
          done
          
          # Retourner le code de sortie du build
          exit $BUILD_RESULT

      - name: Archive Build
        uses: docker://ubuntu:20.04
        shell: bash
        run: |
          # Vérification et archivage des résultats
          if [ -d "${CLOUDBEES_WORKSPACE}/Builds" ]; then
            echo "Artéfacts de build trouvés:"
            find "${CLOUDBEES_WORKSPACE}/Builds" -type f -name "*.apk"
          else
            echo "Aucun artéfact de build trouvé"
            exit 1
          fi
