apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Unity Android Build

on:
  push:
    branches:
      - "main"

jobs:
  build-unity-apk:
    steps:
      - name: Checkout repository
        uses: cloudbees-io/checkout@v1
        
      - name: Activate Unity Personal License
        uses: docker://unityci/editor:ubuntu-6000.0.49f1-android-3.1.0
        shell: sh
        env:
          UNITY_USERNAME: ${{ secrets.UNITY_USERNAME }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        run: |
          unity-editor -batchmode -nographics -quit -logFile /dev/stdout \
          -username "${UNITY_USERNAME}" \
          -password "${UNITY_PASSWORD}" \
          -serial

      - name: Build Android APK
        uses: docker://unityci/editor:6000.0.49f1-android-3
        shell: sh
        run: |
          mkdir -p Builds/Android
          unity-editor \
            -batchmode \
            -nographics \
            -quit \
            -projectPath . \
            -executeMethod BuildScript.Build \
            -logFile build.log || (cat build.log && exit 1)

      - name: Return Unity license (optional)
        uses: docker://unityci/editor:6000.0.49f1-android-3
        shell: sh
        run: |
          unity-editor -batchmode -nographics -quit -returnlicense || true
