apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Unity Android Build1

on:
  push:
    branches:
      - 'main'

jobs:
  build-unity-apk:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1

      - name: Generate Unity license request (.alf)
        uses: docker://unityci/editor:ubuntu-6000.0.49f1-android-3.1.0
        shell: sh
        run: |
          echo "📄 Génération du fichier .alf..."
          mkdir -p unity_lic_request
          unity-editor -batchmode -nographics -createManualActivationFile -logFile /dev/stdout || true
          # Le fichier est généralement nommé Unity_v6000.x.alf
          find ~/.local/share/unity3d -name '*.alf' -exec cp {} unity_lic_request/ \;
          
      - name: Build Unity APK
        uses: docker://unityci/editor:ubuntu-6000.0.49f1-android-3.1.0
        shell: sh
        run: |
          echo "📦 Build APK..."
          mkdir -p Builds/Android
          unity-editor \
            -batchmode \
            -nographics \
            -projectPath . \
            -executeMethod BuildScript.Build \
            -logFile build.log \
            -quit || (cat build.log && exit 1)