apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Unity Version Check

on:
  push:
    branches:
      - 'main'

jobs:
  unity-version:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1

      - name: Check Unity Version
        uses: docker://unityci/editor:ubuntu-2022.3.15f1-base-0.16.1
        shell: sh
        run: |
          echo "🔍 Unity Version:"
          unity-editor --version
