apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Unity Android Build1

on:
  push:
    branches:
      - 'main'

jobs:
  build-unity-apk:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1

      - name: Add Unity license
        uses: docker://unityci/editor:ubuntu-6000.0.49f1-android-3.1.0
        shell: sh
        run: |
          echo "📄 Ajout de la licence Unity..."
          mkdir -p ~/.local/share/unity3d/Unity/
          echo "${{ secrets.UNITY_LICENSE }}" | base64 -d > ~/.local/share/unity3d/Unity/Unity_lic.ulf

      - name: Build Unity APK
        uses: docker://unityci/editor:ubuntu-6000.0.49f1-android-3.1.0
        shell: sh
        run: |
          echo "📦 Build APK..."
          mkdir -p Builds/Android
          unity-editor \
            -batchmode \
            -nographics \
            -projectPath . \
            -executeMethod BuildScript.Build \
            -logFile build.log \
            -quit || (cat build.log && exit 1)
