apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Unity Android Build

on:
  push:
    branches:
      - 'main'

jobs:
  build-unity-apk:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1

      - name: Activate Unity License
        uses: docker://unityci/editor:ubuntu-6000.0.49f1-android-3.1.0
        shell: bash
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        run: |
          echo "🔑 Activating Unity license for CI..."
          xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' \
          unity-editor \
          -batchmode \
          -nographics \
          -username "$UNITY_EMAIL" \
          -password "$UNITY_PASSWORD" \
          -logFile /cloudbees/home/activate.log \
          -quit

      - name: Build Unity APK
        uses: docker://unityci/editor:ubuntu-6000.0.49f1-android-3.1.0
        shell: sh
        run: |
          echo "📦 Build APK..."
          mkdir -p Builds/Android
          unity-editor \
            -batchmode \
            -nographics \
            -projectPath . \
            -executeMethod BuildScript.Build \
            -logFile build.log \
            -quit || (cat build.log && exit 1)